[window]
    dynamic_title = true
    dynamic_padding = false
    dimensions = { columns = 80, lines = 24 }
    decorations = "full"
    padding = { x=15, y=15}

[font.normal]
family = "Terminus"
style = "Regular"

[font.bold]
family = "Terminus"
style = "Bold"

[font.italic]
family = "Terminus"
style = "Italic"

[font.bold_italic]
family = "Terminus"
style = "Bold Italic"

[env]
TERM = "xterm-256color"
