[window]
    dynamic_title = true
    dynamic_padding = false
    dimensions = { columns = 80, lines = 24 }
    decorations = "full"
    padding = { x=15, y=15}
    opacity = 0.9


[env]
TERM = "xterm-256color"
